### ISSUE TITLE
Pouvoir ajouter un boitier à un client ou lui enlever

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#1]
Dans admin.wellcheck.fr, un administrateur doit pouvoir ajouter un boitier à un client ou lui enlever.

En effet, il se bug qu'un bug se passe lors de l'ajout du boitier au compte d'un client ou qu'on souhaite attribuer gratuitement des boitiers à un client.

**Comment by SCcagg5** [comment]
web-app: done

**Comment by flavienbwk** [comment]
@SCcagg5 rajoute une screenshot quand c'est fait stp (demandé dans le sujet du suivi)

**Comment by SCcagg5** [comment]
commit de dev :[https://github.com/SCcagg5/WellcheckV2/commit/d56445cf9af486a57e28c9943f91454f23992044](url)
changelogs:
- ajout du panel admin webapp
- etat de l'api
- possibilité de voir les users (id, nom, prenom, email, phone, date de register)
- possibilite se log sur le compte d'une personne
- possibilite de lui ajouter un boitier depuis son compte

futur url: https://admin.wellcheck/app/

![image](https://user-images.githubusercontent.com/19782751/82342860-6a227580-99f2-11ea-929a-ab3cfd8bae71.png)

**Comment by flavienbwk** [comment]
LGTM

**Comment by flavienbwk** [comment]
En attente du code
