### ISSUE TITLE
Générer un rapport automatique de l'état de la pollution de mes bassins (7 derniers jours)

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#11]
- Format PDF

- Rapport sous forme de tableaux de toutes les mesures + score sur les 7 derniers jours. 1 tableau par boitier.

- Granularité maximale (si le client s'est abonné à 1 mesure / 10 minutes il verra 6 lignes pour chaque heure). Non configurable.

**Comment by SCcagg5** [comment]
format ? pdf ? @flavienbwk

**Comment by flavienbwk** [comment]
![100843787_242834630343234_5399920728944410624_n](https://user-images.githubusercontent.com/14158127/83352019-e731e100-a348-11ea-9878-fcdcf8574a28.png)

**Comment by flavienbwk** [comment]
En attente du code

**Comment by SCcagg5** [comment]
code commit
