### ISSUE TITLE
Savoir comment fonctionne WellCheck

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#12]
Ajouter sur la page d'accueil des screenshots :

- [x] Screenshot dashboard les mesures
- [x] Carte avec flotteurs

**Comment by SCcagg5** [comment]
voir #13 refonte wellcheck.fr

**Comment by flavienbwk** [comment]
![wc_map_floaters](https://user-images.githubusercontent.com/14158127/82752139-3f526b80-9dbc-11ea-8692-1dd623cd39ae.PNG)
![wc_scores](https://user-images.githubusercontent.com/14158127/82752140-40839880-9dbc-11ea-820a-e816f63fc487.PNG)

**Comment by flavienbwk** [comment]
LGTM

**Comment by flavienbwk** [comment]
![image](https://user-images.githubusercontent.com/14158127/83352575-b94e9b80-a34c-11ea-9920-74ee28a7d83e.png)
