### ISSUE TITLE
Boutons d'ajout de bonne ou mauvaise mesure pour chaque boitier

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#15]
Pour qu'on puisse illustrer les alertes au jury, ajouter deux boutons ("Add good measures", "Add polluted measures") dans le détail des mesures des boitiers. Cela aura pour effet d'ajouter une mesure > 95% pour le premier bouton, et une mesure < 50% pour le 2e bouton.

**Comment by SCcagg5** [comment]
![Screenshot_67](https://user-images.githubusercontent.com/19782751/85931094-f82b2f00-b8c1-11ea-937e-6bc3c9166eb0.png)

**Comment by flavienbwk** [comment]
Pourrais-t-on mettre deux vrais boutons pour ça  ("Add good measures", "Add polluted measures") ?

**Comment by SCcagg5** [comment]
code commit mailing lie
