### ISSUE TITLE
Carte du monde ajustée sur mes boitiers

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#3]
Lorsqu'on ouvre la carte, il faut que la vue soit centrée sur l'endroit où sont les boitiers du client.

**Comment by SCcagg5** [comment]
description

**Comment by flavienbwk** [comment]
![centered_map](https://user-images.githubusercontent.com/14158127/82752155-5b560d00-9dbc-11ea-8a0b-475fa5553e15.PNG)

Vérifié, fonctionne.
