### ISSUE TITLE
Pouvoir partager les boitiers de mes partenaires et voir les leurs

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#4]
Le client doit pouvoir partager ses boitiers, arrêter de les partager, et voir les boitiers des personnes qui lui ont partagé leurs boitiers.

**Comment by SCcagg5** [comment]
description

**Comment by flavienbwk** [comment]
![image](https://user-images.githubusercontent.com/14158127/83352066-3aa42f00-a349-11ea-889c-d06ae8b84503.png)
![image](https://user-images.githubusercontent.com/14158127/83352073-54457680-a349-11ea-87ba-74345a69602e.png)

**Comment by flavienbwk** [comment]
En attente du code
