### ISSUE TITLE
Être capable de modifier mes coordonnées bancaires

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#8]

**Comment by SCcagg5** [comment]
web-app: done

**Comment by flavienbwk** [comment]
@SCcagg5 ajouter la screenshot

**Comment by SCcagg5** [comment]
![Screenshot_51](https://user-images.githubusercontent.com/19782751/82125721-3ce28700-97a8-11ea-849c-fb76928278ac.png)
![Screenshot_52](https://user-images.githubusercontent.com/19782751/82125722-3e13b400-97a8-11ea-8946-ded86059c2c5.png)

web-app: done @flavienbwk

**Comment by flavienbwk** [comment]
Parfait
