### ISSUE TITLE
Couleur des points sur la carte mis à jour en fonction de la pollution mesurée à cet endroit

### ISSUE THREAD

**Issue by flavienbwk** [WellCheck-Co/WellCheck#9]
Être capable de visualiser des mesures pour plusieurs bassins en un coup d'œil sur une carte :

- [ ] Cercles vert, orange ou rouge selon la dernière mesure relevée (score)
- [ ] Contours des cercles bleu si les boitiers ne sont pas les miens (partagés)

**Comment by SCcagg5** [comment]
@flavienbwk  || @Reloadaxe possible d'obtenir les images au format svg ?

**Comment by flavienbwk** [comment]
@SCcagg5 tu peux pas utiliser des SVG plutôt ?

**Comment by SCcagg5** [comment]
> @flavienbwk || @Reloadaxe possible d'obtenir les images au format svg ?
> @SCcagg5 tu peux pas utiliser des SVG plutôt ?

Yes, format svg

**Comment by flavienbwk** [comment]
@SCcagg5 mais je veux dire avoir le logo de base des flotteurs en SVG, puis dynamiquement les colorer avec du code, en fonction des scores.

**Comment by flavienbwk** [comment]
![100598780_577762899549633_8313733706279813120_n](https://user-images.githubusercontent.com/14158127/83352046-18121600-a349-11ea-8eb8-0098773a6575.png)

**Comment by flavienbwk** [comment]
En attente du code

**Comment by SCcagg5** [comment]
code commit
